### ISSUE TITLE
Binary win64 of  v 5.0 with -ghl

### ISSUE THREAD

**Issue by fredvs** [rchastain/eschecs#29]
Hello Roland.

Included binary of eschecs.exe 64 bit with heaptrace.

Here on Windows no error nor memory leak.

Could you try it on your system?

[eschecs_win64.zip](https://github.com/rchastain/eschecs/files/3804740/eschecs_win64.zip)

Fre.D

**Comment by rchastain** [comment]
Hello Fred!

Thank you for your efforts.

I get this error (?) message. I don't know what to think about it.

Regards.

Roland
![error](https://user-images.githubusercontent.com/13957204/68141530-fcb76780-ff2d-11e9-9678-172d892f7078.png)

**Comment by fredvs** [comment]
This is the result of heaptrc!

You should get this each time you compile with -ghl.

You may see that there are 0 unfreed memory.

(But maybe you want to advice me for something else...)

**Comment by fredvs** [comment]
But yes, it should be for title of the window "Infos" vs "Error".

Indeed here too it uses the "Error" title in place of "Infos".

I do not know why.
;(

**Comment by fredvs** [comment]
Of course, `-ghl` should not be used for release.

**Comment by rchastain** [comment]
OK Fred. Indeed, I was wondering how to understand the title of the window. And I also wonder if it is important that "heap size" and "free heap" are different. Anyway, you were right, the leak comes from the CommandLine unit.
Thank you!

**Comment by fredvs** [comment]
> And I also wonder if it is important that "heap size" and "free heap" are different

Huh, yes I was thinking the same, by curiosity I will check for light with Google...

Maybe if we discover the memory leak in Linux, it will solve all.
