### ISSUE TITLE
Widgets not visible when the window has been minimized and restored

### ISSUE THREAD

**Issue by rchastain** [rchastain/eschecs#31]
If I minimize the application and restore it, the form is empty: the widgets are not redrawn. The test was made under Windows, with [Eschecs 0.0.5 alpha](https://github.com/rchastain/eschecs/releases/tag/5.0.0).

**Comment by rchastain** [comment]
The problems exists only when using the **maint** branch and when compiling with fpc 64.

It seems to be a fpGUI problem. I made a test with the **nanoedit** example and the result is the same.

**Comment by rchastain** [comment]
I decide to use the **develop** branch now. Problem solved.
I have a little problem with the develop branch but it should be easily fixed.

**Comment by fredvs** [comment]
Hello Roland.

OK, I did jump into your code.
But I did use the source of fpgui-maint (in your source, it is still fpgui-develop).

Also I did change in your code `UpdatePosition` with `UpdateWindowPosition` to be compatible with maint.

And compiled for Win32:
Here all ok after minimize + restore.

But...
Compiled for Win64:
Here blank form after minimize + restore.

So, imho, there is a problem with fpGUI + Win64 bit.

Fre;D

**Comment by rchastain** [comment]
Hello Fred! Thank you for your time.

I had forgotten to commit some modifications for 1.4.1 compatibility. It's done now. I tried a Win32 build and I can confirm what you say.

So, what to do now? Is it really important to have a Win64 build? For me, I would just give up the Win64 compilation. What do you think?

Regards.

Roland

**Comment by rchastain** [comment]
Hello Fred!
I prepared another release candidate. If you have time, you can take a look at it.
https://github.com/rchastain/eschecs/releases/tag/5.0.0.b
I think I can close the both issues.
Regards.
Roland

**Comment by fredvs** [comment]
Hello.

Windows 64 is multi-arch so, imho, better to give only the win32 version, so everybody, even old win32 os could use your software.

Fre;D

**Comment by rchastain** [comment]
Thank you Fred for your answer. Indeed my "win32" package includes some win64 binaries. I will follow your suggestion: I will recompile the launcher for win32 and replace the engines.
Regards.
Roland

**Comment by rchastain** [comment]
Hello Fred!
I remade the package for Win32. Now it contains only Win32 applications.
https://github.com/rchastain/eschecs/releases
Thank you for your help.
If you see another thing to change I will edit the release.
Now I will start to study seriously MSEgui, for _Eschecs_ 6 (to be released in 2025).
Regards.
Roland

**Comment by fredvs** [comment]
Hello Roland.
Super, I will, asap, try deeply your new release.
About MSEgui, welcome and dont hesitate to call me if you have problems.

Fre;D

**Comment by fredvs** [comment]
> Eschecs 6 (to be released in 2025).

Compiled with MSElang?
Maybe if we find partners for MSElang.

But compiled with fpc, you will be impressed how fast you will do the conversion into MSEgui.

Fre;D

**Comment by rchastain** [comment]
OK, thank you Fred. I close the issue.
Regards.
Roland
