### ISSUE TITLE
Menu bar not visible at application start

### ISSUE THREAD

**Issue by rchastain** [rchastain/eschecs#32]
Since I use the _develop_ branch of fpGUI, there is a problem with the menu bar. When the application starts, the menu bar is not visible, until I click on it.
The test was made under Windows.

**Comment by fredvs** [comment]
Hello Roland.
Sorry for the delay.
Imho, you will have more answers if you us the fpGUI mailing list for such problems.

Fre;D

**Comment by fredvs** [comment]
Ooopps, you did it already.
Sorry for the noise.

Fre;D

**Comment by rchastain** [comment]
Thank you for your answer Fred.

**Comment by fredvs** [comment]
Hello Roland.

Not sure that with "develop" branch you will have less problems than "maint".
I am hyper-busy but when I find some time, I will jump into it.

And, at first glance, the problem of refresh after minimize seems much easier to resolve.

Fre;D

**Comment by fredvs** [comment]
Re-re hello.

Did you try to compile Eschecs 5 with the fpGUI source that you used with Eschecs 4?
There was some fixes not yet committed in official "maint" release.

If you use still "develop" branch, you may try the fpg_hint.pas with fixes.
[fpg_hint.pas.zip](https://github.com/rchastain/eschecs/files/3831118/fpg_hint.pas.zip)

Just add fpg_hint.pas in the root-source of Eschecs.

Fre;D

**Comment by rchastain** [comment]
Re-hello Fred!

Yes, I was compiling with the source used in Eschecs 4.

Thank for your file. I try it and come back.

**Comment by rchastain** [comment]
Re-hello Fred!

The file doesn't seem to solve the problem of the invisible menu bar. Maybe we will have an answer coming from the mailing list?

The **develop** branch has problems, but the **maint** branch too. So I thought it would be a good idea to concentrate efforts on **develop** branch, instead of going and coming from the one to the other.

We will see?

Regards.

Roland

**Comment by rchastain** [comment]
Hello Fred! Hope you are well. I discovered some other bugs in **develop** branch, so I wonder if it isn't a better idea to do as you suggest, that is, to use the library used in Eschecs 4 and try to fix little bugs (or even let it as it is).
Have a nice week!
Regards.
Roland

**Comment by fredvs** [comment]
Hello Roland!

Huh, yes, or maybe for next release, if you are still in plan to add the "eaten pieces", and to have a WoW docked application, without problems, re-maybe, it would be a great idea to think to msegui...

You did already the hard work to link all the engines to Pascal, imho, once the conversion fpGUI ---> msegui will be done, there will be no more problems.

Of course my 0,001 CFA.

Fre;D

**Comment by rchastain** [comment]
MSEgui? Yes, why not? It would be great. I have absolutely no experience of MSEgui, but why not? I always desired to learn MSEgui. It could be the occasion.
So I suggest that we release Eschecs 5 as it is, if it is OK for you.
Thank for your money, but you have to know that there are no cents in FCFA. :)
Regards.
Roland

**Comment by fredvs** [comment]
Hello Roland.
See how horrible I am:
https://github.com/bgrabitmap/bgrabitmap/issues/79

Fre;D

**Comment by fredvs** [comment]
Here demo of msegui-chess:

https://github.com/mse-org/mseuniverse/tree/master/samples/widgets/grids/chessboard

**Comment by rchastain** [comment]
> Hello Roland.
> See how horrible I am:
> [bgrabitmap/bgrabitmap#79](https://github.com/bgrabitmap/bgrabitmap/issues/79)
> 
> Fre;D

Very good idea.

**Comment by rchastain** [comment]
> Here demo of msegui-chess:
> 
> https://github.com/mse-org/mseuniverse/tree/master/samples/widgets/grids/chessboard

Of course, I remember that demo.

**Comment by rchastain** [comment]
> Hello Roland.
> See how horrible I am:
> [bgrabitmap/bgrabitmap#79](https://github.com/bgrabitmap/bgrabitmap/issues/79)
> 
> Fre;D

I remember having read somewhere a message by Martin saying that he had a preference for the Graphics32 library. When I have time I will give it an eye.

**Comment by fredvs** [comment]
It seems that it was a fight between the 2 "official old true" graphical library:
**Graphics32** vs **AGG**.

What I like with the new challenger, **BGRABitmap**:
It is pure Pascal (not translated from C), living now, gives access too to last kind of format like **Webp** and much more.

Also you are a big guru of **BGRABitmap**, so nice if there is problems.

Fre;D

**Comment by fredvs** [comment]
Re-hello Roland.
To come back to the topic, I did try the Windows version of your last release.
Indeed, after minimizing, the form is not refreshed.
I did not jump yet into your code but imho adding some "UpdateWindowPosition" or "Refresh" or "ProcessMessages" would work as workaround.

Fre;D

**Comment by rchastain** [comment]
> 
> 
> Re-hello Roland.
> To come back to the topic, I did try the Windows version of your last release.
> Indeed, after minimizing, the form is not refreshed.
> I did not jump yet into your code but imho adding some "UpdateWindowPosition" or "Refresh" or "ProcessMessages" would work as workaround.
> 
> Fre;D

Good idea Fred. But I don't know which event is fired when the the application is restored. I tried the OnShow event but it doesn't work. I will ask the question to Graeme.

Regards.

Roland
