### ISSUE TITLE
About ENGINES.md

### ISSUE THREAD

**Issue by fredvs** [rchastain/eschecs#34]
Hello.

Congratulation for that nice grid!

Could it be possible to have some more info, your feelings, the level, etc..., of each engine?

Or maybe only a column "Rating"  (Class F-J, Class A-E, Expert, Master).

Thanks.

Fre;D

**Comment by rchastain** [comment]
Hello Fred!
Thank for your comment. Good idea. I will see what I can do.
Regards.
Roland

**Comment by rchastain** [comment]
Unfortunately almost all engines are very strong, except mine that are very weak. :)
There is nothing in the middle.
It would be interesting to add support for the Winboard protocol, in order to have more choice. There is a Wb2Uci filter available but it's only for Windows.

**Comment by fredvs** [comment]
Hello.

> except mine that are very weak. :)

Huh, if you say it... (so I am very bad).
OK, I will try first to win against Moustique.

Thanks.

Fre;D
