### ISSUE TITLE
About uos sound libraries.

### ISSUE THREAD

**Issue by fredvs** [rchastain/eschecs#35]
Hello Roland.

Happy new year!

Wow, I am very impressed by all the engines you added, Eschecs is a _must have_ now.

About sound libraries needed by Eschecs.

Only libraries **libPortAudio** and **libMpg123** are needed in Eschecs project.
All others will never be used and should not be added in
 +---audio
|   +---lib

Fre;D

**Comment by fredvs** [comment]
Re-hello.
If you prefer, uos can also load libPortAudio and libMpg123 installed on the system.
In most of all Linux distro those libraries are installed by default.

And so no need to add those libraries in Eschecs dir.

But for Windows it is not the case and asking to people to install libraries on their system is not always welcome.

So the choice is difficult, give a release lighter or  "out-of-the-box"?

**Comment by rchastain** [comment]
Hello Fred!

Happy new year to you!

Glad that you liked the latest release of Eschecs. By the way, it isn't easy to find engines working well _and_ not too strong. We would have more choice if Eschecs supported the XBoard protocol. It is my project for the next major version (the version who will be based on MSEgui).

Thank you for the information about uos. I will remove the not needed files.

So, if I correctly understand you, we could remove the PortAudio and Mpg123 binaries from the Linux package, and let them in the Windows package?

Regards.

Roland

**Comment by fredvs** [comment]
Hello Roland.

> So, if I correctly understand you, we could remove the PortAudio and Mpg123 binaries from the
> Linux package, and let them in the Windows package?

Yes, but at our own risk, If somebody did install Portaudio 18 in place of 19, it will have problems (some distros give Portaudio 18, some others Portaudio 19, uos uses Portaudio 19).

Personally, I prefer to give the binaries of Libraries because I do not like problems.

Fre;D

**Comment by rchastain** [comment]
OK, Fred. So I will let them in, and just remove the libraries that are not used. Thank you.

See you soon!

**Comment by fredvs** [comment]
>  It is my project for the next major version (the version who will be based on MSEgui).

Hello Roland.

I did play with the demo of Martin and did some first change to have the same spirit as Eschecs.
Of course I did not jump yet intro chess-engine stuffs, but only on some bemol of fpGUI, like live changing of pieces and size.

With msegui it works like charm and easy to do.

Here a video of first test using Condal and Wood pieces frpm Eschecs, with size 40x40 and 60x60.
[eschecs_mse.mp4.zip](https://github.com/rchastain/eschecs/files/4033614/eschecs_mse.mp4.zip)

Included the project, maybe you may use it for test at beginning:
[eschecs_mse.zip](https://github.com/rchastain/eschecs/files/4040545/eschecs_mse.zip)

[EDIT] I updated the project files in the zip attachment.
[EDIT2] 09/01/2020, I re-updated the project files in the zip attachment with all sizes and pieces enabled.
             


Fre;D

**Comment by rchastain** [comment]
Hello Fred!

Sorry for the late answer. I hadn't seen that there was a new message.

Thank you very much for your work. I can't wait to take a look at it.

See you very soon!

Best regards.

Roland

**Comment by rchastain** [comment]
Your demo is very nice, Fred.

I am very glad that you involve in this project.

Good night!

**Comment by fredvs** [comment]
Hello Roland.

Nice that you like it!

I do not have plan to jump into auto-play and engines stuff, it is your territory.
But after a very fast look, imho, it will need very few change do make all your  fpGUI-methods work with the mse project.

Fre;D

I will close the issue, it is not related to root title.
