### ISSUE TITLE
Pieces sizes

### ISSUE THREAD

**Issue by fredvs** [rchastain/eschecs#36]
Hello Roland.

I have seen that you added 2 new pieces (magnetic and lucena) and 2 new sizes (30, 90 and 100).

Nice!

But for piece-Wood the new sizes  (30, 90 and 100) are missing, is it wanted?

Fre;D

**Comment by rchastain** [comment]
Hello Fred!

Thank you for your message.

The pieces are generated from TrueType fonts, using a little program of mine, excepted the wood pieces, which come from [here](https://dilena.de/chess-artwork-pieces-and-board-art-assets).

The original files are 80x80. That's why sizes 90 and 100 are missing. Size 30 is missing because I forgot to do it.

I hope I am clear.

Regards.

Roland

**Comment by rchastain** [comment]
By the way, I have another program that generates this style of image (don't know how to name it).
![bk](https://user-images.githubusercontent.com/13957204/72198880-5a879480-3434-11ea-8c3c-55f96ee27894.png)
![wk](https://user-images.githubusercontent.com/13957204/72198881-5a879480-3434-11ea-85e7-b9a89f6c67d0.png)

**Comment by rchastain** [comment]
Uploaded wood pieces size 30.

**Comment by fredvs** [comment]
> By the way, I have another program that generates this style of image (don't know how to name it).
> ![bk](https://user-images.githubusercontent.com/13957204/72198880-5a879480-3434-11ea-8c3c-55f96ee27894.png)
> ![wk](https://user-images.githubusercontent.com/13957204/72198881-5a879480-3434-11ea-85e7-b9a89f6c67d0.png)

Wow, I like it, is it allowed to use it?

**Comment by rchastain** [comment]
Yes, I can upload it. We just have to find a name, and also to decide if we will add that style for each font (and each size). I am afraid that the package become very big! And maybe the style won't look nice for all fonts.

**Comment by rchastain** [comment]
I generated the images for all the fonts. You can download the package here. [link deleted]
There is a problem with Montreal font, I don't know why.
You can add the folders in <eschecs>/images/pieces, with a different name if you don't want to overwrite the old files ("mark-new" for example). The _Options_ application should detect the new folders.
Regards.
Roland
![bk-lucena](https://user-images.githubusercontent.com/13957204/72215204-62b50200-3510-11ea-8cba-5bd663648dea.png)
![bn-condal](https://user-images.githubusercontent.com/13957204/72215205-634d9880-3510-11ea-9677-b46a323215e4.png)
![wb-mark](https://user-images.githubusercontent.com/13957204/72215206-634d9880-3510-11ea-95dd-d65e24d3297a.png)

**Comment by rchastain** [comment]
I opened an issue on the BGRABitmap page for the problem with Chess Montreal.
https://github.com/bgrabitmap/bgrabitmap/issues/84

**Comment by fredvs** [comment]
Hello Roland.
With mse Eschecs there is no problems with Chess Montreal.
But it does not use bgrabitmap but the image-widget of mse.

![eschecs-mse-montreal](https://user-images.githubusercontent.com/3421249/72221321-e1825d00-3559-11ea-858b-1fbd1957c2a9.png)

Fre;D

**Comment by rchastain** [comment]
Hello Fred! Thank you for your message. But we are not talking of the same pictures.
The problem is in the "shaded" pieces. Shaded pictures of the Montreal font are corrupted.
