### ISSUE TITLE
News about Eschecs and MSEgui

### ISSUE THREAD

**Issue by fredvs** [rchastain/eschecs#38]
Hello Roland.

Here on the video, demo of moving pieces from the simulated engine.
Also at end of video, demo using the keyboard.
It is random result, without any check, only to show it in action.

The log memo uses the "notation algébrique figurine (NAF)" but of course you know better what is the best.

I have to do a break with computer but all is ready to welcome your engines code.
Of course all can be changed, but now I feel more comfortable with Eschecs + mse.

Video:

[eschecs_mse_movingpieces.mp4.zip](https://github.com/rchastain/eschecs/files/4109531/eschecs_mse_movingpieces.mp4.zip)

Source:

[Edit: updated in last post]

A bientôt.

Fre;D

**Comment by rchastain** [comment]
Hello Fred! Thank you very much for your demo, which looks very promising.

As I said in a previous discussion, I am working on a console version of _Eschecs_. I will open a new repository for it soon. I would like to improve _Eschecs_ units before embarking on the creation of a new graphical application.

In parallel, I will study your code to start familiarizing myself with MSEgui. Maybe I will create some simple applications (like a chess position viewer), to go step by step to _Eschecs_ v6.

À bientôt mon cher !

Roland

**Comment by rchastain** [comment]
Here is the alpha version of Eschecs Console:
https://github.com/rchastain/eschecs-console

**Comment by fredvs** [comment]
Hello Roland.

Congrats for Eschecs Console!
I will immerse myself in it when I m back in pc world.

Write/read you soon.

Fre;D

**Comment by fredvs** [comment]
Ooops, the previous source zip file has my eschecs.ini file.
Here the source zip without any ini file:

[eschecs_mse.zip](https://github.com/rchastain/eschecs/files/4112130/eschecs_mse.zip)

Bye-bye, I have to leave...

Fre;D

**Comment by rchastain** [comment]
See you soon Fred!

**Comment by fredvs** [comment]
Hello Roland.

Your eschecs-c and his tutorial are **really** great and easy to use.
I can already win against my self!
All is working like charm.
Here video at work:
[strictplayer.mp4.zip](https://github.com/rchastain/eschecs/files/4156840/strictplayer.mp4.zip)

And here the source:
[EDIT] Please use the last source in last post.

I will attack the link to the engines asap.
But not eat all the cake now, let the delicious engines-link for the spring.

Have fun.

Fre;D

**Comment by rchastain** [comment]
Hello Fred!

Nice work. Congratulations!

**Comment by rchastain** [comment]
Re-hello Fred!

I created a repository, starting from the chessboard example of MSEuniverse. The purpose is to familiarize myself my MSEide and MSEgui.

https://github.com/rchastain/msegui-chessboard

In this way, each of us has his hands free to work on his side. I keep your demo next to me to steal ideas from it. ;)

Regards.

Roland

**Comment by fredvs** [comment]
Hello Roland.

Yep, you did it, congrats!
Note this very great feature of mseide/ideU: you may load multiple instances of the ide.

For example you may load a different project for each instance and then, copy-paste mse-widgets from a instance to the other.

Very great if you want for example use my chessboard grid in place of the original one.
Just open my project, copy the chessboard-grid in the mse-designer with Ctrl+C then switch to your project, select your chessboard-grid, delete it and paste mine still in memory into your project.

Incredible but it will work and this for all widgets.

Have fun.

PS1: Using my grid vs the original is just a example of course if you prefer the original, keep it.
PS2: At first touch msegui seems complicated but at the end you will see that is really genius.
[EDIT] PS3: Maybe what could be interesting from my project is how to deal with docking forms (not very easy to understand with msegui) and how to do the animations.

Fre;D

**Comment by fredvs** [comment]
Some very last fixes in source:
[EDITED2] Updated zip without my eschecs.ini and updated prj file.
[eschecs_mse.zip](https://github.com/rchastain/eschecs/files/4171001/eschecs_mse.zip)

**Comment by rchastain** [comment]
Thank you Fred !
