### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by fredvs** [rchastain/eschecs#39]
Hello Roland.

What version of BGRABitmap are you using?
Here, with last BGRABitmap I get this error:

> /home/fred/Downloads/eschecs-master/source/board.pas(214,33) Error: (4025) Incompatible type for arg no. 3: Got "LongInt", expected "Boolean"
> /home/fred/bgrabitmap-dev-bgrabitmap/bgrabitmap/bgranoguibitmap.pas(119,28) Hint: (5039) Found declaration: Draw(TCanvas;TRect;Boolean=`TRUE`);
> /home/fred/bgrabitmap-dev-bgrabitmap/bgrabitmap/bgranoguibitmap.pas(114,28) Hint: (5039) Found declaration: Draw(TCanvas;LongInt;LongInt;Boolean=`TRUE`);
> board.pas(549) Fatal: (10026) There were 1 errors compiling module, stopping
> Fatal: (1018) Compilation aborted

**Comment by fredvs** [comment]
Re-hello Roland.

Ooops, much things to add to make the compiler happy using your "MakeFile" with "make".
_-dBGRABITMAP_USE_FPGUI_ was missing.

OK, I stop, it is too difficult to find all the dependencies without any prj or lpi project file.

I close the issue.

**Comment by rchastain** [comment]
Sorry Fred. The _Makefile_ is experimental. :)

I think it should work if you edit _extrafpc.cfg_ (to fix the libraries path).

Otherwise feel free to create your Lazarus or MSEide project.

Regards.

Roland

**Comment by fredvs** [comment]
Hello Roland.

Yep, indeed, updating extrafpc.cfg did the trick but it stops with this:

_

> Compiling eco.pas
> eschecs.pas(377,13) Error: Identifier not found "ICmdLineParams"
> eschecs.pas(377,27) Error: Error in type definition

_

By the way, from where is "ICmdLineParams", when I created a  _prj_ for your project, I stopped about it too.

**Comment by rchastain** [comment]
> 
> By the way, from where is "ICmdLineParams", when I created a _prj_ for your project, I stopped about it too.

It's fpGUI, the _develop_ branch.

**Comment by fredvs** [comment]
> It's fpGUI, the develop branch.

Ha, ok, I used the _maint_ branch.

Ok, it compiles now.

But running gives a crash, I suppose it is because the init file or the engines or something is not installed.

```
fred@fiens ~/D/e/source> ./eschecs 
AfterCreate
InitForm
Destroy
An unhandled exception occurred at $0000000000403B77:
EInOutError: File not found
  $0000000000403B77
  $0000000000409FF0
  $000000000040A05E

Destroy
An unhandled exception occurred at $000000000055F074:
EAccessViolation: Access violation
  $000000000055F074
  $000000000040454E
  $0000000000445D76
  $000000000041B97B
  $0000000000420267
  $000000000040A05E

```

**Comment by fredvs** [comment]
Allez, the last for tonight.

OK, the binary must be in -FE..
So, now it runs but directly stop with a error "Out of Memory"

![eschecs_error](https://user-images.githubusercontent.com/3421249/115306332-f8096200-a167-11eb-8f82-ec2eaa526364.png)

Maybe this has to do with something not installed, so I will stop to annoy you.

**Comment by rchastain** [comment]
Thank you for testing the program, Fred, and sorry for the pain. :)

I have made some work to solve (I hope) the issue. I changed the location of the log file. It was hidden in the _config_ folder: now it will be created in executable directory. I disabled temporarily the style manager, because it crashes in debug mode (using the _develop_ branch). I tried to better manage the case where the executable doesn't find files: now it can run even without the pictures. I hope it will help.

There are other problems with the _develop_ branch. It works better if you compile with `-B` in release mode.

Regards.

Roland

**Comment by rchastain** [comment]
Other topic. Do you remember how you made _icon.inc?_ If yes, could you explain? I would like, if possible, to replace the white background with a transparent one.

**Comment by fredvs** [comment]
Hello Roland.

> Do you remember how you made icon.inc? 

More or less.

For the original icon, I used _Gimp_ to convert it into _png_  (or maybe _bmp_, I dont remember witch works) format.

Then I used fpGUI _designer_ext_ and his "Tools" "Image Convertor":
https://github.com/fredvs/uidesigner_ext/releases

![image_convertor](https://user-images.githubusercontent.com/3421249/115390252-53763700-a1de-11eb-8af2-f2d8ee7b776b.png)

Then copy the code generated and paste it in _icon.inc_, keeping the original name of the icon.

**Comment by rchastain** [comment]
Thank you Fred.
