### ISSUE TITLE
Can you support Korean chess?

### ISSUE THREAD

**Issue by cjssh1002** [rchastain/eschecs#40]
Can you support Korean chess?

**Comment by rchastain** [comment]
Unfortunately I don't know Korean chess, so it is unlikely to happen.

**Comment by cjssh1002** [comment]
It seems like a simple problem if you only set the movement rules for Korean chess pieces. I use a fairy stockfish engine.
The outcome of the game is determined by the engine settings.

**Comment by rchastain** [comment]
Simple to say, but not so simple to do. I don't even know the rules of that game. And I don't have motivation for doing it. Sorry.
